name: another-action
on: [push]
jobs: 
  write-to-console:
  name: Write to console
    steps:
      - run: echo 'Alta Vista Baby'
  testing: 
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
